version: '2'
services:
    kedbapp-app:
        image: kedbapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://kedbapp-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=kedbApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=kedbapp-elasticsearch:9300
        ports:
            - 9999:9999
    kedbapp-mongodb:
        extends:
            file: mongodb.yml
            service: kedbapp-mongodb
    kedbapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: kedbapp-elasticsearch
